min_version = "2025.1.14"

[tools]
node = "23.11.0"
cargo-binstall = "1.10.15"
"npm:lefthook" = "1.8.5"
"npm:@commitlint/config-conventional" = "19.6.0"
"npm:@commitlint/cli" = "19.6.0"
"npm:@commitlint/types" = "19.5.0"
"npm:remark-cli" = "12.0.1"
"npm:remark-validate-links" = "8.0.0"
"npm:remark-lint-no-dead-urls" = "1.1.0"
"aqua:cue-lang/cue" = "0.12.1"
"cargo:sd" = "1.0.0"

[tasks."fmt"]
depends = ["fmt:cue"]

[tasks."lint"]
depends = ["lint:docs"]

[tasks."test"]
depends = ["test:cue"]

[tasks."fmt:cue"]
run = "cue fmt $(mise run find:cue)"

[tasks."lint:cue"]
run = "echo 'cue: pass'"

[tasks."lint:docs"]
run = "mise run remark ."

[tasks."test:cue"]
run = "cue vet --inject-vars --concrete $(mise run find:cue)"

[tasks."find:cue"]
run = "find \"$MISE_PROJECT_ROOT\" -type f -name '*.cue'"

[tasks."remark"]
run = """
#!/usr/bin/env bash
set -euo pipefail
REMARK_VALIDATE_LINKS="$(mise where npm:remark-validate-links)/lib/node_modules/remark-validate-links/index.js"
REMARK_LINT_NO_DEAD_URLS="$(mise where npm:remark-lint-no-dead-urls)/lib/node_modules/remark-lint-no-dead-urls/index.js"
remark --ignore-path .gitignore --ignore-pattern CHANGELOG.md --quiet --frail --no-stdout --use "$REMARK_VALIDATE_LINKS" --use "$REMARK_LINT_NO_DEAD_URLS" "$@"
"""

[tasks."commitlint"]
run = "commitlint --extends \"$(mise where npm:@commitlint/config-conventional)/lib/node_modules/@commitlint/config-conventional/lib/index.js\""

[tasks."hurl:cue"]
run = """
#!/usr/bin/env bash
set -euo pipefail
git add $(mise run find:cue)
git commit --message "feat: update cue files"
git pull
git push
"""
